AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

# Enable blue/green deployments using this Globals section. For instructions, see the AWS CodeStar User Guide:
# https://docs.aws.amazon.com/codestar/latest/userguide/how-to-modify-serverless-project.html?icmpid=docs_acs_rm_tr
#
# Globals:
#   Function:
#     AutoPublishAlias: live
#     DeploymentPreference:
#       Enabled: true
#       Type: Canary10Percent5Minutes

Resources:  
  spms:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/spms/spms.handler
      Runtime: nodejs4.3
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        spmsProfileApi:
          Type: Api
          Properties:
            Path: /spms/profiles/{studentid}
            Method: any
        spmsPersonalinfoApi:
          Type: Api
          Properties:
            Path: /spms/personalinfo/{studentid}
            Method: any
  ConfigLambdaPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
    - spmsGetStudentProfile
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref spmsGetStudentProfile
      Principal: apigateway.amazonaws.com
  UserTable1:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: "studentsprofile"
      AttributeDefinitions:
        - AttributeName: studentid
          AttributeType: S
      KeySchema:
        - AttributeName: studentid
          KeyType: HASH
      ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5      